name: Python package
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Run create_authorized_keys.py script
      uses: jannekem/run-python-script-action@v1
      with: 
        script: create_authorized_keys.py
      # run: |
      #   python create_authorized_keys.py